routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('concerts/categories/{id}', 'ConcertController@indexByCategory')->name('concertsCategories');
Route::get('artistes/tags/{id}', 'ArtisteController@indexByTag')->name('artistesTags');
Route::get('medias/concerts/{id}','MediaController@indexByConcert')->name('mediasConcerts');
Route::get('ajoutPaniers/{id}','DateController@ajoutPanier')->name('paniers');
Route::get('paniers/{id}','DateController@indexPanier')->name('panier');
Route::get('commandes/users/{id}','CommandeController@indexByUser')->name('commandesUsers');
Route::get('ligneCommande','CommandeController@ligneCommande')->name('ligneCommande');
Route::resource('artistes','ArtisteController');
Route::resource('concerts','ConcertController');
Route::resource('categories','CategorieController');
Route::resource('tags','TagController');
Route::resource('medias','MediaController');
Route::resource('dates','DateController');
Route::resource('commandes','CommandeController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Media.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    protected $fillable=['name','type','link', 'concert_id'];

    public $table = "medias";

    public function concert(){
        return $this->belongsTo('App\Concert');
    }
}

app/Http/Controllers/MediaController.php
<?php

namespace App\Http\Controllers;

use App\Concert;
use App\Media;
use Illuminate\Http\Request;

class MediaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $medias=Media::with('concert')->get();
        $medias=Media::paginate(5);
        return view('/medias/index',['medias'=> $medias]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $concerts = Concert::pluck('name', 'id');
        return view('medias/create',compact('concerts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $media=Media::create($request->all());
        $medias=Media::with('concerts')->get();
        return redirect()->route('medias.index',['medias'=>$medias]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $media=Media::findOrFail($id);
        return view('/medias/show',['media'=>$media]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $media=Media::findOrFail($id);
        return view('/medias/update',['media'=>$media]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $media=Media::findOrFail($id);
        $media->update($request->all());
        return redirect('/medias');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $media= Media::find($id);
        $media->delete();
        return redirect()->route('medias.index');
    }

    public function indexByConcert($id){
        $concert= Concert::findOrFail($id);
        $medias=Media::where('concert_id','=',$concert->id)->get();
        return view('/medias/index',['medias'=> $medias]);
    }
}

resources/views/medias/create.blade.php
@extends ('layouts.master')

@section('title')
    <title>Create media</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/medias">Home</a></li>
        <li><a href="/medias/1/edit">Update</a> </li>
        <li><a href="/medias">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::open(['route' => 'medias.store']) !!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('name', 'Name :')}}
            {{Form::text('name', 'Name')}}
        </div>
        <div class="form-group">
            {{Form::label('link', 'Lien :')}}
            {{Form::text('link', null)}}
        </div>
        <div class="form-group">
            {{Form::label('type', 'Type :')}}
            {{Form::number('type', 'Type')}}
        </div>
        <div class="form-group">
            {{Form::label('concert_id', 'Concert :')}}
            {{Form::select('concert_id', $concerts)}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop

resources/views/medias/index.blade.php
@extends ('layouts.master')

@section('title')
    <title>Home</title>
@stop

@section('header')

@stop
@section('content')
    <h1>Mes médias</h1>
    <div class="row">
        @foreach($medias as $media)

                <div class="col-lg-4 mb-4 text-dark">
                    <div class="card h-100">
                        <h4 class="card-header">{{$media->name}}</h4>
                        <div class="card-body">
                            <p class="card-text"><video width="400"><source src="{{$media->link}}"></video></p>
                        </div>
                        <div class="card-footer">
                            <a href="{{route('medias.show',['media'=>$media->id])}}" class="btn btn-dark">Learn More</a>
                        </div>
                    </div>
                </div>


            <article class="col-sm-6 text-center border border-secondary rounded">
                <iframe width="450" height="315" src="{{$media->link}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <span>Type du media : {{$media->type}}</span>
                <span>Concert lié au media : <a href="{{"/concerts/".$media->concert->id}}">{{$media->concert->name}}</a></span>
                <a href="{{ route('medias.edit',['media' => $media->id]) }}" class="btn btn-secondary text-center w-25">Editer</a>
                <form action="{{ route('medias.destroy', ['id' => $media->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger text-center w-25">DELETE</button>
                    </div>
                </form>
            </article>
        @endforeach
    </div>

@stop

resources/views/medias/show.blade.php
@extends ('layouts.master')

@section('title')
    <title>View media {{$media->id}}</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/medias">Home</a></li>
        <li><a href="{{"/medias/".$media->id."/edit"}}">Edit</a></li>
        <li><a href="/medias">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    <div class="row">
        <article class="col-sm-6 text-center border border-secondary rounded">
            <span>{{$media->name}}</span>
            <span> {{$media->type}}</span>
            <iframe width="420" height="315"
                    src="{{$media->link}}">
            </iframe>
        </article>
    </div>
@stop

resources/views/medias/update.blade.php
@extends ('layouts.master')

@section('title')
    <title>Update medias</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/medias">Home</a></li>
        <li><a href="/medias/create">Create</a></li>
        <li><a href="/medias/2/edit">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::model($media,['method' => 'put', 'route' => ['medias.update',$media->id]])!!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('name', 'Name :')}}
            {{Form::text('name', null)}}
        </div>
        <div class="form-group">
            {{Form::label('link', 'Lien :')}}
            {{Form::text('link', null)}}
        </div>
        <div class="form-group">
            {{Form::label('type', 'Type :')}}
            {{Form::number('type', null)}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop