routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('concerts/categories/{id}', 'ConcertController@indexByCategory')->name('concertsCategories');
Route::get('artistes/tags/{id}', 'ArtisteController@indexByTag')->name('artistesTags');
Route::get('medias/concerts/{id}','MediaController@indexByConcert')->name('mediasConcerts');
Route::get('ajoutPaniers/{id}','DateController@ajoutPanier')->name('paniers');
Route::get('paniers/{id}','DateController@indexPanier')->name('panier');
Route::get('commandes/users/{id}','CommandeController@indexByUser')->name('commandesUsers');
Route::get('ligneCommande','CommandeController@ligneCommande')->name('ligneCommande');
Route::resource('artistes','ArtisteController');
Route::resource('concerts','ConcertController');
Route::resource('categories','CategorieController');
Route::resource('tags','TagController');
Route::resource('medias','MediaController');
Route::resource('dates','DateController');
Route::resource('commandes','CommandeController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Commande.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Commande extends Model
{
    protected $fillable = ['id','paiement','status','prixTotal','user_id'];

    public function dates(){
        return $this->belongsToMany('App\Date');
    }

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/CommandeController.php
<?php

namespace App\Http\Controllers;

use App\Commande;
use App\Date;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CommandeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $commandes=Commande::with('user')->get();
        $commandes=Commande::paginate(5);
        return view('/commandes/index',['commandes'=> $commandes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::pluck('name', 'id');
        $user = Auth::id();
//        $prix = Date::where(User::find($user));
//        dd($user = User::find($id)->dates);
        return view('commandes/create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::id();
        $commande = Commande::create($request->all());
        $panier = User::find(Auth::id());
        $commande->save();
        $panier->dates()->detach();
        return redirect()->route('commandesUsers',compact('user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Commande  $commande
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $commande=Commande::findOrFail($id);
        return view('/commandes/show',['commande'=>$commande]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Commande  $commande
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $commande=Commande::findOrFail($id);
        $user = User::pluck('name', 'id');
        return view('commandes/update',compact('commande','user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Commande  $commande
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $commande=Commande::findOrFail($id);
        $commande->update($request->all());
//        $commande->user()->attach($request->user());
        return redirect('/commandes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Commande  $commande
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $commande = Commande::find($id);
        $commande->delete();
        $user = Auth::id();
        return redirect()->route('commandesUsers',compact('user'));
    }

    public function ligneCommande(){


        $ligneCmd = User::find(Auth::id());
        $ligneCmd->dates()->detach();
        $user = Auth::id();
        return redirect()->route('commandesUsers',compact('user'));

    }

    public function indexByUser($id){
        $user= User::findOrFail($id);
        $commandes=Commande::where('user_id','=',$user->id)->get();
        return view('/commandes/user',['commandes'=> $commandes]);
    }
}

resources/views/commandes/create.blade.php
@extends ('layouts.master')

@section('title')
    <title>Create commande</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/commandes">Home</a></li>
        <li><a href="/commandes/edit/1">Update</a> </li>
        <li><a href="/commandes">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::open(['route' => 'commandes.store'],$user,$prix) !!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('paiement', 'Type de paiement :')}}
            {{Form::text('paiement', 'Paiement')}}
        </div>
        <div class="form-group">
            {{Form::label('status', 'Status de la commande :')}}
            {{Form::text('status', 'Status')}}
        </div>
        <div class="form-group">
            {{Form::label('prixTotal', 'Prix :')}}
            {{Form::number('prixTotal', $prix)}}
        </div>
        <div class="form-group">
            {{Form::hidden('user_id', $user)}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop

resources/views/commandes/index.blade.php
@extends ('layouts.master')

@section('title')
    <title>Home</title>
@stop

@section('header')

@stop
@section('content')
    <h1>Mes commandes</h1>
    <div class="row">
        @foreach($commandes as $commande)

                <div class="col-lg-4 mb-4 text-dark">
                    <div class="card h-100">
                        <h4 class="card-header"><a class="text-dark" href={{"/commandes/".$commande->id}}>{{$commande->id}}</a></h4>
                        <div class="card-body">
                            <p class="card-text">Prix : {{$commande->prixTotal}} €</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{route('commandes.show',['commande'=>$commande->id])}}" class="btn btn-dark">Learn More</a>
                        </div>
                    </div>
                </div>


            <article class="col-sm-6 text-center border border-secondary rounded">
                <a href="{{"/users/".$commande->user_id}}">Numéro client : {{$commande->user_id}}</a>
                <span>Status du paiement : {{$commande->status}}</span>
                <span>Type du paiement : {{$commande->paiement}}</span>
                {{--@foreach($commande->concerts as $concert)--}}
                    {{--<span><a href="{{"/concerts/".$concert->id}}">{{$concert->name}}</a></span>--}}
                {{--@endforeach--}}
                {{--@foreach($commande->tags as $tag)--}}
                    {{--<span><a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a></span>--}}
                {{--@endforeach--}}
                <a href="{{ route('commandes.edit',['commande' => $commande->id]) }}" class="btn btn-secondary text-center w-25">Editer</a>
                <form action="{{ route('commandes.destroy', ['id' => $commande->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger text-center w-25">DELETE</button>
                    </div>
                </form>
            </article>
        @endforeach
    </div>

@stop

resources/views/commandes/show.blade.php
@extends ('layouts.master')

@section('title')
    <title>View commande {{$commande->id}}</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/commandes">Home</a></li>
        <li><a href="{{"/commandes/".$commande->id."/edit"}}">Edit</a></li>
        <li><a href="/commandes">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    <div class="row">
        <article class="col-sm-6 text-center border border-secondary rounded">
            <a href="{{"/commandes/".$commande->id}}">Voici la commande {{$commande->id}}</a>
            <span>Type de paiement : {{$commande->paiement}}</span>
            <span>Status de la commande : {{$commande->status}}</span>
            <span>Prix total : {{$commande->prixTotal}}</span>
            <span>La commande appartient à l'utilisateur {{$commande->user_id}}</span>
            {{--@foreach($commande->concerts as $concert)--}}
                {{--<a href="{{"/concerts/".$concert->id}}">{{$concert->name}}</a>--}}
            {{--@endforeach--}}
            {{--@foreach($commande->tags as $tag)--}}
                {{--<a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a>--}}
            {{--@endforeach--}}
        </article>
    </div>
@stop

resources/views/commandes/update.blade.php
@extends ('layouts.master')

@section('title')
    <title>Update commande</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/commandes">Home</a></li>
        <li><a href="/commandes/create">Create</a></li>
        <li><a href="/commandes/2/edit">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::model($commande,['method' => 'put', 'route' => ['commandes.update',$commande->id]])!!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('paiement', 'Type de paiement :')}}
            {{Form::text('paiement', null)}}
        </div>
        <div class="form-group">
            {{Form::label('status', 'Status de la commande :')}}
            {{Form::text('status', null)}}
        </div>
        <div class="form-group">
            {{Form::label('prixTotal', 'Prix :')}}
            {{Form::number('prixTotal', null)}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop

resources/views/commandes/user.blade.php
@extends ('layouts.master')

@section('title')
    <title>Home</title>
@stop

@section('header')

@stop
@section('content')
    <h1>Mes commandes</h1>
    <div class="row">
        @foreach($commandes as $commande)

                <div class="col-lg-4 mb-4 text-dark">
                    <div class="card h-100">
                        <h4 class="card-header"><a class="text-dark" href={{"/commandes/".$commande->id}}>{{$commande->id}}</a></h4>
                        <div class="card-body">
                            <p class="card-text">Prix : {{$commande->prixTotal}} €</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{route('commandes.show',['commande'=>$commande->id])}}" class="btn btn-dark">Learn More</a>
                        </div>
                    </div>
                </div>


            <article class="col-sm-6 text-center border border-secondary rounded">
                <a href="{{"/users/".$commande->user_id}}">Numéro client : {{$commande->user_id}}</a>
                <span>Status du paiement : {{$commande->status}}</span>
                <span>Type du paiement : {{$commande->paiement}}</span>
                {{--@foreach($commande->concerts as $concert)--}}
                    {{--<span><a href="{{"/concerts/".$concert->id}}">{{$concert->name}}</a></span>--}}
                {{--@endforeach--}}
                {{--@foreach($commande->tags as $tag)--}}
                    {{--<span><a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a></span>--}}
                {{--@endforeach--}}
                <a href="{{ route('commandes.edit',['commande' => $commande->id]) }}" class="btn btn-secondary text-center w-25">Editer</a>
                <form action="{{ route('commandes.destroy', ['id' => $commande->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger text-center w-25">DELETE</button>
                    </div>
                </form>
            </article>
        @endforeach
    </div>

@stop