routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('concerts/categories/{id}', 'ConcertController@indexByCategory')->name('concertsCategories');
Route::get('artistes/tags/{id}', 'ArtisteController@indexByTag')->name('artistesTags');
Route::get('medias/concerts/{id}','MediaController@indexByConcert')->name('mediasConcerts');
Route::get('ajoutPaniers/{id}','DateController@ajoutPanier')->name('paniers');
Route::get('paniers/{id}','DateController@indexPanier')->name('panier');
Route::get('commandes/users/{id}','CommandeController@indexByUser')->name('commandesUsers');
Route::get('ligneCommande','CommandeController@ligneCommande')->name('ligneCommande');
Route::resource('artistes','ArtisteController');
Route::resource('concerts','ConcertController');
Route::resource('categories','CategorieController');
Route::resource('tags','TagController');
Route::resource('medias','MediaController');
Route::resource('dates','DateController');
Route::resource('commandes','CommandeController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Artiste.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Concert;

class Artiste extends Model
{
    protected $fillable=['name','biography','logo','instragram','youtube','bandcamp','siteweb'];

    public function concerts(){
        return $this->belongsToMany('App\Concert');
    }

    public function tags(){
        return $this->belongsToMany('App\Tag');
    }
}

app/Http/Controllers/ArtisteController.php
<?php

namespace App\Http\Controllers;

use App\Artiste;
use App\Concert;
use App\Http\Requests\StoreArtiste;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ArtisteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $artistes=Artiste::all();
        $artistes=Artiste::with('concerts','tags')->get();
        $artistes = Artiste::paginate(5);
        return view('/artistes/index',['artistes'=> $artistes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $concerts = Concert::pluck('name','id');
        $tags = Tag::pluck('name','id');
        return view('artistes/create',compact('concerts','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreArtiste $request)
    {
        $artiste=Artiste::create($request->all());
        $artiste->tags()->sync($request->tags);
        $artiste->concerts()->sync($request->concerts);
        $artiste->logo = $artiste->id . '.' .
            $request->file('logo')->getClientOriginalExtension();
//        dd($picture);
        $request->file('logo')->move(
            base_path() . '/public/img/', $artiste->logo
        );
        $artiste->logo='/img/'.$artiste->logo;
//        $logo = $request->file('logo').$picture->store('logo ');
        $artiste->save();
//        $artistes=Artiste::with('concerts','tags')->get();

        return redirect()->route('artistes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Artiste  $artiste
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $artiste=Artiste::findOrFail($id);
        return view('/artistes/show',['artiste'=>$artiste]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Artiste  $artiste
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $artiste=Artiste::findOrFail($id);
        $concerts = Concert::pluck('name','id');
        $tags = Tag::pluck('name','id');
        return view('artistes/update',compact('concerts','tags','artiste'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Artiste  $artiste
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $artiste=Artiste::findOrFail($id);
        $artiste->update($request->all());
        $artiste->tags()->sync($request->tags);
        $artiste->concerts()->sync($request->concerts);
        return redirect('/artistes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Artiste  $artiste
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $artiste = Artiste::find($id);
        $artiste->tags()->detach();
        $artiste->concerts()->detach();
        $artiste->delete();
        return redirect()->route('artistes.index');
    }

    public function indexByTag($id){
        $tag = Tag::find($id);
        $artistes=$tag->artistes;
        return view('/artistes/index',['artistes'=> $artistes]);
    }
}

resources/views/artistes/create.blade.php
@extends ('layouts.master')

@section('title')
    <title>Create artiste</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/artistes">Home</a></li>
        <li><a href="/artistes/edit/1">Update</a> </li>
        <li><a href="/artistes">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::open(['route' => 'artistes.store','files'=>true]) !!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('name', 'Name :')}}
            {{Form::text('name', 'Name')}}
        </div>
        <div class="form-group">
            {{Form::label('biography', 'Description :')}}
            {{Form::textarea('biography', 'Description')}}
        </div>
        <div class="form-group">
            {{Form::label('instagram', 'Instagram :')}}
            {{Form::text('instagram', 'Instagram')}}
        </div>
        <div class="form-group">
            {{Form::label('youtube', 'Youtube :')}}
            {{Form::text('youtube', 'Youtube')}}
        </div>
        <div class="form-group">
            {{Form::label('bandcamp', 'Bandcamp :')}}
            {{Form::text('bandcamp', 'Bandcamp')}}
        </div>
        <div class="form-group">
            {{Form::label('siteweb', 'Site :')}}
            {{Form::text('siteweb', 'Site')}}
        </div>
        <div class="form-group">
            {{Form::label('tags', 'Tag :')}}
            {{Form::select('tags[]', $tags,null,['multiple' => 'multiple'])}}
        </div>
        <div class="form-group">
            {{Form::label('concerts', 'Concert :')}}
            {{Form::select('concerts[]', $concerts,null,['multiple' => 'multiple'])}}
        </div>
        <div class="form-group">
            {{Form::label('logo', 'Lien image :  ')}}
            {{Form::file('logo', null)}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop

resources/views/artistes/index.blade.php
@extends ('layouts.master')

@section('title')
    <title>Artistes</title>
@stop

@section('header')

@stop
@section('content')
    <h1>Mes artistes</h1>
    <div class="row">
        @foreach($artistes as $artiste)

                <div class="col-lg-4 mb-4 text-dark">
                    <div class="card h-100">
                        <h4 class="card-header">{{$artiste->name}}</h4>
                        <div class="card-body">
                            <p class="card-text">{{$artiste->biography}}</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{route('artistes.show',['artiste'=>$artiste->id])}}" class="btn btn-dark">Learn More</a>
                        </div>
                    </div>
                </div>


            <article class="col-sm-6 text-center border border-secondary rounded">
                <a href="{{"/artistes/".$artiste->id}}"><img src=" {{$artiste->logo}}" alt="{{$artiste->name}}"></a>
                <p>{{$artiste->biography}}</p>
                <ul class="nav navbar-dark">
                    <li><i class="fab fa-instagram"><a href="{{$artiste->instagram}}">Instagram</a></i></li>
                    <li><i class="fab fa-youtube"><a href="{{$artiste->youtube}}">Youtube</a></i></li>
                    <li><i class="fab fa-bandcamp"><a href="{{$artiste->bandcamp}}">Bandcamp</a></i></li>
                    <li><i class="fab fa-firefox"><a href="{{$artiste->siteweb}}">Site Web</a></i></li>
                </ul>
                @foreach($artiste->concerts as $concert)
                    <span>Concert :<a href="{{"/concerts/".$concert->id}}">{{$concert->name}}</a></span>
                @endforeach
                @foreach($artiste->tags as $tag)
                    <span>Tag :<a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a></span>
                @endforeach
                <a href="{{ route('artistes.edit',['artiste' => $artiste->id]) }}" class="btn btn-secondary text-center w-25">Editer</a>
                <form action="{{ route('artistes.destroy', ['id' => $artiste->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger text-center w-25">DELETE</button>
                    </div>
                </form>
            </article>
        @endforeach
            {{$artistes -> links()}}
    </div>

@stop

resources/views/artistes/show.blade.php
@extends ('layouts.master')

@section('title')
    <title>View artiste {{$artiste->id}}</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/artistes">Home</a></li>
        <li><a href="{{"/artistes/".$artiste->id."/edit"}}">Edit</a></li>
        <li><a href="/artistes">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    <div class="row">
        <article class="col-sm-6 text-center border border-secondary rounded">
            <p>Voici l'artiste {{$artiste->name}}</p>
            <a href="{{"/artistes/".$artiste->id}}"><img src=" {{$artiste->logo}}" alt="{{$artiste->name}}"></a>
            <p> {{$artiste->biography}}</p>
            @foreach($artiste->concerts as $concert)
                <a href="{{"/concerts/".$concert->id}}">{{$concert->name}}</a>
            @endforeach
            @foreach($artiste->tags as $tag)
                <span><a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a></span>
            @endforeach
        </article>
    </div>
@stop

resources/views/artistes/update.blade.php
@extends ('layouts.master')

@section('title')
    <title>Update artiste</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/artistes">Home</a></li>
        <li><a href="/artistes/create">Create</a></li>
        <li><a href="/artistes/2/edit">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::model($artiste,['method' => 'put', 'route' => ['artistes.update',$artiste->id],'files'=>true])!!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('name', 'Name :')}}
            {{Form::text('name', null)}}
        </div>
        <div class="form-group">
            {{Form::label('biography', 'Description :')}}
            {{Form::textarea('biography', null)}}
        </div>
        <div class="form-group">
            {{Form::label('instagram', 'Instagram :')}}
            {{Form::text('instagram', null)}}
        </div>
        <div class="form-group">
            {{Form::label('youtube', 'Youtube :')}}
            {{Form::text('youtube', null)}}
        </div>
        <div class="form-group">
            {{Form::label('bandcamp', 'Bandcamp :')}}
            {{Form::text('bandcamp', null)}}
        </div>
        <div class="form-group">
            {{Form::label('siteweb', 'Site :')}}
            {{Form::text('siteweb', null)}}
        </div>
        <div class="form-group">
            {{Form::label('logo', 'Lien image :  ')}}
            {{Form::file('logo', null)}}
        </div>
        <div class="form-group">
            {{Form::label('tags', 'Tag :')}}
            {{Form::select('tags[]', $tags,null,['multiple' => 'multiple'])}}
        </div>
        <div class="form-group">
            {{Form::label('concerts', 'Concert :')}}
            {{Form::select('concerts[]', $concerts,null,['multiple' => 'multiple'])}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop