routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('concerts/categories/{id}', 'ConcertController@indexByCategory')->name('concertsCategories');
Route::get('artistes/tags/{id}', 'ArtisteController@indexByTag')->name('artistesTags');
Route::get('medias/concerts/{id}','MediaController@indexByConcert')->name('mediasConcerts');
Route::get('ajoutPaniers/{id}','DateController@ajoutPanier')->name('paniers');
Route::get('paniers/{id}','DateController@indexPanier')->name('panier');
Route::get('commandes/users/{id}','CommandeController@indexByUser')->name('commandesUsers');
Route::get('ligneCommande','CommandeController@ligneCommande')->name('ligneCommande');
Route::resource('artistes','ArtisteController');
Route::resource('concerts','ConcertController');
Route::resource('categories','CategorieController');
Route::resource('tags','TagController');
Route::resource('medias','MediaController');
Route::resource('dates','DateController');
Route::resource('commandes','CommandeController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Date.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Date extends Model
{
    protected $fillable=['date','prix','concert_id','user_id','quantite','prix'];

    public function concert(){
        return $this->belongsTo('App\Concert');
    }

    public function users(){
        return $this->belongsToMany('App\User');
    }

    public function commandes(){
        return $this->belongsToMany('App\Commande');
    }
}

app/Http/Controllers/DateController.php
<?php

namespace App\Http\Controllers;

use App\Commande;
use App\Concert;
use App\Date;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use function Sodium\increment;

class DateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dates=Date::with('concert')->get();
        $dates=Date::paginate(5);
        return view('/dates/index',['dates'=> $dates]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $concert = Concert::pluck('name', 'id');
//        $users = User::pluck('name', 'id');
//        $commandes = Commande::pluck('name','id');
        return view('dates/create',compact('concert'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $date=Date::create($request->all());
        $date->concert()->sync($request->concert);
//        $date->users()->sync($request->users);
//        $date->commandes()->sync($request->commandes);
        $date->save();
        return redirect()->route('dates.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Date  $date
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $date=Date::findOrFail($id);
        return view('/dates/show',['date'=>$date]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Date  $date
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $date=Date::findOrFail($id);
        $concert = Concert::pluck('name','id');
//        $users = User::pluck('name','id');
        return view('dates/update',compact('date','concert'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Date  $date
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $date=Date::findOrFail($id);
        $date->update($request->all());
        $date->concert()->sync($request->concert);
        return redirect('/dates');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Date  $date
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dates = Date::find($id);
        $dates->delete();
        return redirect()->route('dates.index');
    }

    public function ajoutPanier($id){
        $date = Date::findOrFail($id);
//        dd($request->all());
//        dd($date->users);
        $date->save();
        $concert = Concert::pluck('name','id');
//        $date->users()->attach(Auth::id(),['quantite'=> +1]);
        $date->users()->sync(array(Auth::id()=>array('quantite'=> 1,'prix'=>$date->prix)));

        return redirect()->route('dates.index',compact('concert'));
    }

    public function indexPanier($id){
        $paniers = User::find($id)->dates;
//        dd($paniers);
        if($paniers->isEmpty()){
            return redirect()->route('dates.index');
        }
        $concert = Concert::pluck('name','id');
//        dd($paniers);
        return view ('dates/panier',compact('paniers','concert'));

    }

}

resources/views/dates/create.blade.php
@extends ('layouts.master')

@section('title')
    <title>Create date</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/dates">Home</a></li>
        <li><a href="/dates/edit/1">Update</a> </li>
        <li><a href="/dates">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::open(['route' => 'dates.store']) !!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('date', 'Date :')}}
            {{Form::date('date',  \Carbon\Carbon::now())}}
        </div>
        <div class="form-group">
            {{Form::label('prix', 'Prix :')}}
            {{Form::number('prix', 0)}}
        </div>
        <div class="form-group">
            {{Form::label('concert_id', 'Concert :')}}
            {{Form::select('concert_id', $concert)}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop

resources/views/dates/index.blade.php
@extends ('layouts.master')

@section('title')
    <title>Home</title>
@stop

@section('header')

@stop
@section('content')
    <h1>Mes dates</h1>
    <div class="row">
        @foreach($dates as $date)

                <div class="col-lg-4 mb-4 text-dark">
                    <div class="card h-100">
                        <h4 class="card-header">{{$date->date}}</h4>
                        <div class="card-body">
                            <p class="card-text">{{$date->prix}} euros</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{route('dates.show',['date'=>$date->id])}}" class="btn btn-dark">Learn More</a>
                        </div>
                    </div>
                </div>


            <article class="col-sm-6 text-center border border-secondary rounded">
                <a href="{{"/dates/".$date->id}}"></a>
                <p>{{$date->prix}} euros</p>
                <span><a href="{{"/concerts/".$date->concert->id}}">{{$date->concert->name}}</a></span>
                {{--@foreach($date->tags as $tag)--}}
                    {{--<span><a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a></span>--}}
                {{--@endforeach--}}
                <span>
                    <a href="{{ route('paniers',['date' => $date->id,$quantite=5]) }}" class="btn btn-light text-center w-25">Ajouter</a>
                </span>
                    <a href="{{ route('dates.edit',['date' => $date->id]) }}" class="btn btn-secondary text-center w-25">Editer</a>
                <form action="{{ route('dates.destroy', ['id' => $date->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger text-center w-25">DELETE</button>
                    </div>
                </form>
            </article>
        @endforeach
            {{$dates -> links()}}
    </div>

@stop

resources/views/dates/panier.blade.php
@extends ('layouts.master')

@section('title')
    <title>Home</title>
@stop

@section('header')

@stop
@section('content')
    <h1>Mon panier</h1>
    <div class="row">
        @foreach($paniers as $panier)

            <div class="col-lg-4 mb-4 text-dark">
                <div class="card h-100">
                    <h4 class="card-header">{{$panier->date}}</h4>
                    <div class="card-body">
                        <p class="card-text">{{$panier->concert->name}}</p>
                        <p class="card-text">{{$panier->prix}} euros</p>
                        <p class="card-text">{{$panier->pivot_user_id}}</p>
                        <p class="card-text">{{$panier->pivot_quantite}}</p>
                    </div>
                    <div class="card-footer">
                        <a href="{{route('dates.show',['date'=>$panier->id])}}" class="btn btn-dark">Learn More</a>
                    </div>
                </div>
            </div>


            <article class="col-sm-6 text-center border border-secondary rounded">
                <a href="{{"/concerts/".$panier->concert->id}}">{{$panier->concert->name}}</a>
                <p>{{$panier->prix}} euros</p>
                <span><a href="{{"/concerts/".$panier->id}}">{{$panier->date}}</a></span>
                {{--@foreach($date->tags as $tag)--}}
                {{--<span><a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a></span>--}}
                {{--@endforeach--}}
            </article>
        @endforeach
    </div>
    <span class="">
        <a href="{{ route('commandes.create',['date' => $panier->id]) }}" class="btn btn-light text-center w-25">Valider</a>
    </span>
@stop

resources/views/dates/show.blade.php
@extends ('layouts.master')

@section('title')
    <title>View date {{$date->id}}</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/dates">Home</a></li>
        <li><a href="{{"/dates/".$date->id."/edit"}}">Edit</a></li>
        <li><a href="/dates">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    <div class="row">
        <article class="col-sm-6 text-center border border-secondary rounded">
            <p>Voici la date {{$date->date}}</p>
            <p> {{$date->prix}}</p>
            {{--@foreach($date->concerts as $concert)--}}
                {{--<a href="{{"/concerts/".$concert->id}}">{{$concert->name}}</a>--}}
            {{--@endforeach--}}
            {{--@foreach($date->tags as $tag)--}}
                {{--<a href="{{"/tags/".$tag->id}}">{{$tag->name}}</a>--}}
            {{--@endforeach--}}
        </article>
    </div>
@stop

resources/views/dates/update.blade.php
@extends ('layouts.master')

@section('title')
    <title>Update date</title>

@stop

@section('header')
    <ul class="nav navbar-dark">
        <li><a href="/dates">Home</a></li>
        <li><a href="/dates/create">Create</a></li>
        <li><a href="/dates/2/edit">Contact</a></li>
        <li><a href="{{ url('/logout') }}"
               onclick="event.preventDefault();
             document.getElementById('logout-form').submit();">
                Logout
            </a>

            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
@stop
@section('content')
    {!! Form::model($date,['method' => 'put', 'route' => ['dates.update',$date->id]])!!}
    <div class="col-lg-2">
        <div class="form-group">
            {{Form::label('date', 'Date :')}}
            {{Form::date('date',date('Y-m-d', strtotime($date->date)))}}
        </div>
        <div class="form-group">
            {{Form::label('prix', 'prix :')}}
            {{Form::number('prix', null)}}
        </div>
        <div class="form-group">
            {{Form::label('concert_id', 'Concert :')}}
            {{Form::select('concert_id', $concert,null)}}
        </div>
        <div class="form-group">
            {{Form::submit('Envoyer')}}
        </div>
    </div>
    {!! Form::close() !!}
    <div class="row">
        <article class="col-sm-3">

        </article>
    </div>
@stop